hwi_oauth:
    resource_owners:
        google:
            type:                google
            client_id:           '%env(GOOGLE_CLIENT_ID)%'
            client_secret:       '%env(GOOGLE_CLIENT_SECRET)%'
            scope:               "email profile"
            options:
               csrf: true
               refresh_on_expire: true
        linkedin:
            type:           linkedin
            client_id:      '%env(LINKEDIN_CLIENT_ID)%'
            client_secret:  '%env(LINKEDIN_CLIENT_SECRET)%'
            scope:          "r_liteprofile r_emailaddress"
            options:
               csrf: true
               refresh_on_expire: true
        azure:
            type:          azure
            client_id:     <client_id>
            client_secret: <client_secret>
            options:
                application: common
                csrf: true
                refresh_on_expire: true