hwi_oauth:
    resource_owners:
        github:
            type:                github
            client_id:           <github_client_id>
            client_secret:       <github_client_secret>
            scope:               'user:email,public_repo'
            options:
               csrf: true
               refresh_on_expire: true
        google:
            type:                google
            client_id:           <google_client_id>
            client_secret:       <google_client_secret>
            scope:               "email profile"
            options:
               csrf: true
               refresh_on_expire: true
        linkedin:
            type:           linkedin
            client_id:      <client_id>
            client_secret:  <client_secret>
            scope:          <scope>
            options:
               csrf: true
               refresh_on_expire: true
        azure:
            type:          azure
            client_id:     <client_id>
            client_secret: <client_secret>
            options:
                application: common
                csrf: true
                refresh_on_expire: true