twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/assets/styles': styles
    globals:
        epsi_name: '%env(EPSI_NAME)%'
        epsi_tel: '%env(EPSI_TEL)%'
        epsi_address: '%env(EPSI_ADDRESS)%'
        base_title: '%env(BASE_TITLE)%'
        base_title_admin: '%env(BASE_TITLE_ADMIN)%'

when@test:
    twig:
        strict_variables: true