twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/assets/styles': styles
    globals:
        invoice_name: '%env(INVOICE_NAME)%'
        invoice_tel: '%env(INVOICE_TEL)%'
        invoice_address: '%env(INVOICE_ADDRESS)%'
        base_title: '%env(BASE_TITLE)%'
        base_title_admin: '%env(BASE_TITLE_ADMIN)%'

when@test:
    twig:
        strict_variables: true