# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    stripe_api_public_key: '%env(STRIPE_API_PUBLIC_KEY)%'
    stripe_api_private_key: '%env(STRIPE_API_PRIVATE_KEY)%'

    mailer_sender: '%env(MAILER_SENDER)%'
    mailer_contact: '%env(MAILER_CONTACT)%'

    invoice_base_path: '%kernel.project_dir%/public/assets/upload/invoices/'
    mails_base_path: '%kernel.project_dir%/templates/mails/'
    
    .container.dumper.inline_factories: true
    social_media:
        instagram: https://www.instagram.com/alumni.montpellier
        linkedin: https://www.linkedin.com/company/alumni-epsi-wis-montpellier

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    hwi_oauth.user.provider.entity:
        class: App\Security\EntityUserProvider
        arguments:
            $class: App\Entity\User
            $properties:
                'google': 'googleId'
                'linkedin': 'linkedinId'
                'azure': 'microsoftId'

    Twig\Extension\StringLoaderExtension:

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    League\CommonMark\Extension\Table\TableExtension:
        tags:
            - { name: twig.markdown.league_extension }